SWE546 Final Project - Method 1

In this method, SGD is used and two matrices (A and B) is obtained so that their product gives the minimum error with the ratings we know. 

Movielens 10M data set is used. The data set is divided into 2 part, one to be used for training, the other to be used for testing. 

The execution time for finding A and B was too long so only 10 iteration is performed. The result matrices are stored for future use to analyse performance metrics. 

After the A and B is found, the test data is used to calculate accuracy, precision, recall, TPR and FPR. These metrics are calculated by selecting a threshold of 4 as rating and the expectation was if the rating in the test data is >= than the threshold, then the prediction must also be >= than the threshold and the other way around. Any prediction that does not follow this metric is counted as either false positive or false negative. 

The performance metrics can be found as printed at end of this notebook.



In [2]:
import numpy as np
import pandas as pd
import time


rnames = ['user_id', 'movie_id', 'rating', 'timestamp'] 
mnames = ['MovieID', 'Title', 'Genres']
ratings = pd.read_table('../data/ml-10M100K/ratings.dat', sep='::',engine='python', header=None, names=rnames)
train = pd.read_table('../data/ml-10M100K/ra.train', sep='::',engine='python', header=None, names=rnames)
test = pd.read_table('../data/ml-10M100K/ra.test', sep='::',engine='python', header=None, names=rnames)
movies = pd.read_table('../data/ml-10M100K/movies.dat', sep='::',engine='python', header=None, names=mnames)

In [4]:
ratings

user_id  movie_id  rating  timestamp
0               1       122       5  838985046
1               1       185       5  838983525
2               1       231       5  838983392
3               1       292       5  838983421
4               1       316       5  838983392
5               1       329       5  838983392
6               1       355       5  838984474
7               1       356       5  838983653
8               1       362       5  838984885
9               1       364       5  838983707
10              1       370       5  838984596
11              1       377       5  838983834
12              1       420       5  838983834
13              1       466       5  838984679
14              1       480       5  838983653
15              1       520       5  838984679
16              1       539       5  838984068
17              1       586       5  838984068
18              1       588       5  838983339
19              1       589       5  838983778
20              1       594       5  838984679
21              1       616       5  838984941
22              2       110       5  868245777
23              2       151       3  868246450
24              2       260       5  868244562
25              2       376       3  868245920
26              2       539       3  868246262
27              2       590       5  868245608
28              2       648       2  868244699
29              2       719       3  868246191
...           ...       ...     ...        ...
10000024    71567      1396       3  912580688
10000025    71567      1407       2  912578457
10000026    71567      1527       5  912580647
10000027    71567      1580       3  912580688
10000028    71567      1584       3  912580647
10000029    71567      1598       2  912649143
10000030    71567      1690       3  912578406
10000031    71567      1717       1  912578457
10000032    71567      1721       4  912649271
10000033    71567      1748       3  912580647
10000034    71567      1769       3  912649037
10000035    71567      1792       2  912649171
10000036    71567      1805       4  912649010
10000037    71567      1833       3  912649171
10000038    71567      1876       3  912580722
10000039    71567      1909       2  912580688
10000040    71567      1917       4  912580787
10000041    71567      1920       4  912578247
10000042    71567      1982       1  912580553
10000043    71567      1983       1  912580553
10000044    71567      1984       1  912580553
10000045    71567      1985       1  912580553
10000046    71567      1986       1  912580553
10000047    71567      2012       3  912580722
10000048    71567      2028       5  912580344
10000049    71567      2107       1  912580553
10000050    71567      2126       2  912649143
10000051    71567      2294       5  912577968
10000052    71567      2338       2  912578016
10000053    71567      2384       2  912578173

[10000054 rows x 4 columns]

In [5]:
train

user_id  movie_id  rating   timestamp
0              1       370     5.0   838984596
1              1       377     5.0   838983834
2              1       420     5.0   838983834
3              1       466     5.0   838984679
4              1       480     5.0   838983653
5              1       520     5.0   838984679
6              1       539     5.0   838984068
7              1       586     5.0   838984068
8              1       588     5.0   838983339
9              1       589     5.0   838983778
10             1       594     5.0   838984679
11             1       616     5.0   838984941
12             2       780     3.0   868244698
13             2       786     3.0   868244562
14             2       802     2.0   868244603
15             2       858     2.0   868245645
16             2      1049     3.0   868245920
17             2      1073     3.0   868244562
18             2      1210     4.0   868245644
19             2      1356     3.0   868244603
20             2      1391     3.0   868246006
21             2      1544     3.0   868245920
22             3      1552     2.0  1133571139
23             3      1564     4.5  1136418605
24             3      1597     4.5  1133571226
25             3      1674     4.5  1133571182
26             3      3408     4.0  1164885590
27             3      3684     4.5  1136075915
28             3      4535     4.0  1164885526
29             3      4677     4.0  1136075924
...          ...       ...     ...         ...
9301244    71567      1396     3.0   912580688
9301245    71567      1407     2.0   912578457
9301246    71567      1527     5.0   912580647
9301247    71567      1580     3.0   912580688
9301248    71567      1584     3.0   912580647
9301249    71567      1598     2.0   912649143
9301250    71567      1690     3.0   912578406
9301251    71567      1717     1.0   912578457
9301252    71567      1721     4.0   912649271
9301253    71567      1748     3.0   912580647
9301254    71567      1769     3.0   912649037
9301255    71567      1792     2.0   912649171
9301256    71567      1805     4.0   912649010
9301257    71567      1833     3.0   912649171
9301258    71567      1876     3.0   912580722
9301259    71567      1909     2.0   912580688
9301260    71567      1917     4.0   912580787
9301261    71567      1920     4.0   912578247
9301262    71567      1982     1.0   912580553
9301263    71567      1983     1.0   912580553
9301264    71567      1984     1.0   912580553
9301265    71567      1985     1.0   912580553
9301266    71567      1986     1.0   912580553
9301267    71567      2012     3.0   912580722
9301268    71567      2028     5.0   912580344
9301269    71567      2107     1.0   912580553
9301270    71567      2126     2.0   912649143
9301271    71567      2294     5.0   912577968
9301272    71567      2338     2.0   912578016
9301273    71567      2384     2.0   912578173

[9301274 rows x 4 columns]

In [6]:
test

user_id  movie_id  rating   timestamp
0             1       122     5.0   838985046
1             1       185     5.0   838983525
2             1       231     5.0   838983392
3             1       292     5.0   838983421
4             1       316     5.0   838983392
5             1       329     5.0   838983392
6             1       355     5.0   838984474
7             1       356     5.0   838983653
8             1       362     5.0   838984885
9             1       364     5.0   838983707
10            2       110     5.0   868245777
11            2       151     3.0   868246450
12            2       260     5.0   868244562
13            2       376     3.0   868245920
14            2       539     3.0   868246262
15            2       590     5.0   868245608
16            2       648     2.0   868244699
17            2       719     3.0   868246191
18            2       733     3.0   868244562
19            2       736     3.0   868244698
20            3       110     4.5  1136075500
21            3       151     4.5  1133571026
22            3       213     5.0  1136075789
23            3       590     3.5  1136075494
24            3      1148     4.0  1133571121
25            3      1246     4.0  1133570967
26            3      1252     4.0  1133571071
27            3      1276     3.5  1133571205
28            3      1288     3.0  1133571035
29            3      1408     3.5  1133571145
...         ...       ...     ...         ...
698750    71565         6     3.0   974382722
698751    71565        21     3.0   974382722
698752    71565        34     5.0   974295597
698753    71565        73     5.0   974295350
698754    71565       110     4.0   974382753
698755    71565       111     4.0   974295321
698756    71565       246     4.0   974295208
698757    71565       260     4.0   974294884
698758    71565       265     4.0   974295708
698759    71565       318     4.0   974295467
698760    71566         1     5.0   830340834
698761    71566        17     4.0   830341029
698762    71566        22     4.0   830341137
698763    71566        25     4.0   830341062
698764    71566        32     4.0   830340972
698765    71566        34     4.0   830340993
698766    71566        36     5.0   830341071
698767    71566        50     4.0   830341018
698768    71566        58     4.0   830341109
698769    71566        62     3.0   830341051
698770    71567        32     3.0   912580647
698771    71567       110     5.0   912578269
698772    71567       196     4.0   912580787
698773    71567       256     3.0   912580753
698774    71567       260     5.0   912649271
698775    71567       316     4.0   912580753
698776    71567       442     2.0   912580787
698777    71567       480     4.0   912580688
698778    71567       589     4.0   912580647
698779    71567       780     4.0   912580753

[698780 rows x 4 columns]

In [3]:
Ys = np.mat(train)
Ys

matrix([[  1.00000000e+00,   3.70000000e+02,   5.00000000e+00,
           8.38984596e+08],
        [  1.00000000e+00,   3.77000000e+02,   5.00000000e+00,
           8.38983834e+08],
        [  1.00000000e+00,   4.20000000e+02,   5.00000000e+00,
           8.38983834e+08],
        ..., 
        [  7.15670000e+04,   2.29400000e+03,   5.00000000e+00,
           9.12577968e+08],
        [  7.15670000e+04,   2.33800000e+03,   2.00000000e+00,
           9.12578016e+08],
        [  7.15670000e+04,   2.38400000e+03,   2.00000000e+00,
           9.12578173e+08]])

In [4]:
Yt = np.mat(test)
Yt

matrix([[  1.00000000e+00,   1.22000000e+02,   5.00000000e+00,
           8.38985046e+08],
        [  1.00000000e+00,   1.85000000e+02,   5.00000000e+00,
           8.38983525e+08],
        [  1.00000000e+00,   2.31000000e+02,   5.00000000e+00,
           8.38983392e+08],
        ..., 
        [  7.15670000e+04,   4.80000000e+02,   4.00000000e+00,
           9.12580688e+08],
        [  7.15670000e+04,   5.89000000e+02,   4.00000000e+00,
           9.12580647e+08],
        [  7.15670000e+04,   7.80000000e+02,   4.00000000e+00,
           9.12580753e+08]])

In [5]:
Ym = np.mat(movies)

Nr = 71567 # Number of users
Nc = 10681 # Number of movies

Nid = 65133 # Max movie index

#MovieIDs are from 1 to 65133 but there is ratings for only 10681 movies in the data set.
#There is a mapping between the MovieID and index is needed. 
MovieMap = np.mat(np.zeros((Nid, 1)))

size = Ym.shape[0]

for i in range(size):
    MovieMap[Ym[i, 0]-1, 0] = i

MovieMap

matrix([[  0.00000000e+00],
        [  1.00000000e+00],
        [  2.00000000e+00],
        ..., 
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  1.06800000e+04]])

In [20]:
Nk = 2

#Start with random A and B
A = np.mat(np.random.rand(Nr, Nk))
B = np.mat(np.random.rand(Nk, Nc))

#Number of iterations are kept at 10 because of the execution time
EPOCH = 10
Eta = 0.05
eta = Eta

start_time = time.clock()

Ysize = Ys.shape[0]

for i in range(EPOCH):    
    for k in range(Ysize):
        u = Ys[k,0] - 1
        m = Ys[k,1] - 1
        m_idx = MovieMap[m, 0]
        err = Ys[k,2] - A[u,:]*B[:,m_idx]
        
        temp_A = A[u,:] + eta*err[0,0]*B[:,m_idx].T
        B[:,m_idx]   = B[:,m_idx] + eta*err[0,0]*A[u,:].T
        A[u,:]   = temp_A
    
    eta = Eta*1./(i+1)

time_sgd = time.clock() - start_time
print time_sgd, "seconds"

#Save the A and B matrices for future use - no need to run this cell again
A.dump("matrixA.dat")
B.dump("matrixB.dat")



6916.45 seconds


/home/yesim/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:25: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/home/yesim/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:26: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [24]:
A = np.load("matrixA.dat")
A

matrix([[ 1.65280637,  1.88101146],
        [ 0.76248237,  1.20261728],
        [ 0.95834816,  1.64353172],
        ..., 
        [ 1.27394563,  1.3091596 ],
        [ 1.52035809,  1.23438469],
        [ 1.438594  ,  0.95890416]])

In [25]:
B = np.load("matrixB.dat")
B

matrix([[ 0.23770542,  0.80324166,  0.76156334, ...,  1.12340907,
          0.7149995 ,  1.44162324],
        [ 0.65595517,  0.12163754,  0.06734896, ...,  1.54459447,
          0.68618707,  1.5625731 ]])

In [23]:
testSize = Yt.shape[0]

np.random.shuffle(Yt)

#The threshold is chosen to be 4. Every rating above 4 will be counted as "good" and every rating below 
#will be caounted as "bad" rating. 
metric_threshold = 4


TP = 0;
FP = 0; 
TN = 0;
FN = 0;

for t in range(testSize):
    user = Yt[t, 0] - 1
    movie = Yt[t, 1] - 1
    m_index = MovieMap[movie, 0]
    
    rating = Yt[t, 2]
    
    #Find out the prediction for the user, movie pair in the test data (A*B)
    predict = A[user,:]*B[:,m_index]
    
    if (rating >= metric_threshold and predict >= metric_threshold):
        TP += 1
    elif (rating < metric_threshold and predict < metric_threshold):
        TN += 1
    elif (rating > metric_threshold and predict < metric_threshold):
        FN += 1
    elif (rating < metric_threshold and predict > metric_threshold):
        FP += 1
    
if ((TP + FN) == 0 ):
    TPR = 0
else:
    TPR = float(TP / float(TP+FN))
if ((FP + TN) == 0 ):
    FPR = 0
else:
    FPR = float(FP / float(FP+TN))
        
print('truePos = ' + repr(TP) + ', trueNeg = ' + repr(TN) + 
      ', falsePos = ' + repr(FP) + ', falseNeg = ' + repr(FN) + '\n')

print('True Positive Rate = ' + repr(TPR) + ', False Positive Rate = ' + repr(FPR) + '\n')

accuracy = float((TP + TN) / float(TP + FP + TN + FN)) * 100
precision = float(TP / float(TP + FP)) * 100
recall = float(TP / float(TP + FN)) * 100

print('accuracy = ' + repr(accuracy) + '%, precision = ' + repr(precision) + 
      '%, recall = ' + repr(recall) + '%\n')


truePos = 158666, trueNeg = 275355, falsePos = 35189, falseNeg = 86059

True Positive Rate = 0.6483440596588007, False Positive Rate = 0.11331405533515379

accuracy = 78.16409704125388%, precision = 81.84777281989115%, recall = 64.83440596588007%

